name: Test Secret Access

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check if API_KEY secret is accessible
        env:
          MY_SECRET: ${{ secrets.API_KEY }}
        run: |
          if [ -z "$MY_SECRET" ]; then
            echo "Secret API_KEY is not accessible or empty."
            exit 1
          else
            echo "Secret API_KEY is accessible."
          fi
