name: Test and Build Flask App for OpenWeatherMap

on:
  workflow_dispatch:
    inputs:
      runTest:
        description: 'Run tests (true/false)'
        required: true
        type: boolean
        default: false
      logErrors:
        description: 'Log errors if tests fail (true/false)'
        required: true
        type: boolean
        default: false

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install pytest
        run: |
          pip install pytest  # Ensure pytest is installed
          
      - name: Run Unit Tests
        run: |
          pytest unittest_Rajneet.py
        env:
          GREETING: "Running unit tests for application logic"
          API_KEY: ${{ secrets.API_KEY}}  # API Key from Secrets
          
      - name: Run Integration Tests
        run: |
          pytest integrationtest_Rajneet.py
        env:
          API_KEY: ${{ secrets.API_KEY}}  # API Key from Secrets

      - name: Confirm Test Output
        run: |
          echo "$GREETING"
          export EXPECTED_RESULT="All tests passed"
          echo "Expected Result: $EXPECTED_RESULT"
          
      - name: Upload log file on failure
        if: ${{ github.event.inputs.logErrors == 'true' && (steps.run_unittest_tests.outcome == 'failure' || steps.run_integration_test.outcome == 'failure') }}
        uses: actions/upload-artifact@v3
        with:
          name: test_failure_logs
          path: test_output.log

  build-job:
    runs-on: ubuntu-latest
    needs: test-job
    if: success()  # Only runs if the test-job was successful
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies for Flask App
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Flask app
        env:
          FLASK_APP: "app.py"  # Replace with your actual app filename
          FLASK_ENV: development
        run: |
          nohup python -m flask run --host=0.0.0.0 &
          sleep 5
          
      - name: Confirm Build Status
        run: |
          echo "Flask application is running"
          echo "Build job completed successfully."
      
      - name: Upload Error Log if Available
        if: ${{ github.event.inputs.log_errors == 'true' && needs.test-job.outputs.error_log_exists == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: error_log
          path: error_logs/error_log.txt
