name: Test and Build Flask App for OpenWeatherMap

on:
  workflow_dispatch:
    inputs:
      runTest:
        description: 'Run tests (true/false)'
        required: true
        type: boolean
        default: false
      logErrors:
        description: 'Log errors if tests fail (true/false)'
        required: true
        type: boolean
        default: false

env:
  API_KEY: ${{ secrets.API_KEY }}
 
jobs:
  test-OpenWeatherMap:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest 

      - name: Run Unit Tests
        if: ${{ github.event.inputs.runTest == 'true' }}
        run: pytest unittest_Rajneet.py
        
      - name: Run Integration Tests
        if: ${{ github.event.inputs.runTest == 'true' }}
        run: pytest integrationtest_Rajneet.py


      - name: Upload Error Log if Available
        if: ${{ github.event.inputs.logErrors == 'true' && failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test_failure_logs
          path: test_output.log
        continue-on-error: true

  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    needs: test-and-run-flask-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_RAJNEET_USERNAME }}
          password: ${{ secrets.DOCKER_RAJNEET_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build --build-arg API_KEY=${{ secrets.API_KEY }} -t ektuhi123/owm_api_rajneet:latest .
          docker push ektuhi123/owm_api_rajneet:latest
