name: Test and Build Flask App for OpenWeatherMap

on: 
 push: 
  branches:
   - rajneet_branch

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Unit Tests
        run: |
          pytest Test_app.py
        env:
          GREETING: "Running tests for application logic"
          
      - name: Run Integration Tests
        run: |
          pytest Test_app.py

      - name: Confirm Test Output
        run: |
          echo "$GREETING"
          echo "Expected Result: $EXPECTED_RESULT"

  build-job:
    runs-on: ubuntu-latest
    needs: test-job
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Application
        run: echo "Building application as tests passed successfully."
        env:
          BUILD_MESSAGE: "Application build started."

      - name: Confirm Build Status
        run: |
          echo "$BUILD_MESSAGE"
          echo "Build job completed successfully."
