name: Test-OPWM-APP

on:
  workflow_dispatch:
    inputs:
      runTest:
        required: true
        type: boolean
        default: false
      logErrors:
        required: true
        type: boolean
        default: false

jobs:
  test_openweathermap_ubuntu:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run unittest tests and redirect output to log file
      - name: Run unittest tests
        if: ${{ github.event.inputs.runTest == 'true' }}
        id: run_unittest_tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python -m unittest discover -s . -p "unittest_herman.py" 2>&1 | tee unittest_error.log
        continue-on-error: true  # Allow job to continue even if the test fails
        # Capture exit code for later checks
        # Save exit code to be used in condition for uploading logs
        env:
          UNITTEST_EXIT_CODE: ${{ steps.run_unittest_tests.outcome }}

      # Start Flask app
      - name: Run Flask app
        env:
          FLASK_APP: "app.py"  # Replace with your actual app filename
          FLASK_ENV: development
        run: |
          nohup python -m flask run --host=0.0.0.0 &
          sleep 5  # Give the server a few seconds to start

      # Run integration test and redirect output to log file
      - name: Run integration test
        id: run_integration_test
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python integrationtest_herman.py 2>&1 | tee integration_error.log
        continue-on-error: true  # Allow job to continue even if the test fails
        # Capture exit code for later checks
        env:
          INTEGRATION_TEST_EXIT_CODE: ${{ steps.run_integration_test.outcome }}

      # Upload log files if a test fails
      - name: Upload error logs
        if: |
          ${{ github.event.inputs.logErrors == 'true' }} &&
          ( steps.run_unittest_tests.outcome == 'failure' || steps.run_integration_test.outcome == 'failure' )
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: |
            unittest_error.log
            integration_error.log

  build_and_publish_docker:
    runs-on: ubuntu-latest
    needs: test_openweathermap_ubuntu
    if: success()  # Only runs if all previous steps succeed
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/opwm-api:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/opwm-api:latest
